server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: zhanhaodi
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 # 使用0号链接库
    host: localhost
    port: 6379
    password: zhanhaodi
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: zhanhaodi
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hardyz.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出sql语句
    map-underscore-to-camel-case: true # 使得mybatis支持驼峰命名法
logging:
  level:
    root: info
    com.hardyz.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"
# jwt令牌校验信息配置
emos:
  jwt:
    # 密钥
    password: hardyz
    # 过期时间 天
    expire: 5
    # 缓存过期时间 天
    cache-expire: 10


